# Dependencies
markdown:         kramdown
pygments:         false
highlighter:      rouge
mathjax:          true


# Permalinks
permalink:        pretty

# Setup
title:            DyCo 
tagline:          'Dynamiques Couplées -- Coupled Dynamics'
description:      'METTRE À JOUR LA DESCRIPTION ICI'
url:              http://lanyon.getpoole.com
logo:             "/assets/images/apple-touch-icon-144-precomposed.png"

author:
  name:           'DyCo'
  url:            http://dyco.lied.univ-paris-diderot.fr/
  avatar:         "/assets/images/apple-touch-icon-144-precomposed.png"

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/dyco-uparis/DyCo

theme: jekyll-theme-slate
