# Dependencies
markdown:         kramdown
pygments:         false
highlighter:      rouge
mathjax:          true


# Permalinks
permalink:        pretty

# Setup
title:            DyCo 
tagline:          'Dynamiques Couplées -- Coupled Dynamics'
description:      "Dyco
Dyco est une équipe du laboratoire [LIED](http://www.lied-pieri.univ-paris-diderot.fr/) de l'[université de Paris](https://u-paris.fr/) qui s'intéresse à la thermodynamique hors d'équilibre et à ses conséquences sur le monde qui nous entoure"
url:              http://lanyon.getpoole.com
#logo:             "/public/apple-touch-icon-144-precomposed.png"

author:
  name:           'DyCo'
  url:            http://dyco.lied.univ-paris-diderot.fr/
  avatar:         "/public/apple-touch-icon-144-precomposed.png"

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/dyco-uparis/DyCo

theme: jekyll-theme-slate
