source "https://rubygems.org"

gem "jekyll", "~> 3.8"
gem "jekyll-sitemap", "~> 0.13"
gem "jekyll-mentions", "~> 1.2"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-seo-tag", "~> 2.3"
gem "jekyll-redirect-from", "~> 0.12"
gem "jekyll-default-layout", "~> 0.1"
gem "jekyll-feed", "~> 0.9"
gem "jemoji", "~> 0.9"
gem "jekyll-theme-slate"
gem "jekyll-gist"
gem "kramdown", ">= 2.3.1"
gem "nokogiri", ">= 1.11.4"
gem "rexml", ">= 3.2.5"
